### ISSUE TITLE
Check if a tags directory exists before adding it.

### ISSUE THREAD

**Issue by Aerocatia** [MosesofEgypt/mozzarilla#22]
Mozzarilla should check a directory exists before adding it to the list.

There is also an issue with invalid directories being used while kdialog is installed as standard output can contain things other than what is expected as seen in the attached image. This also applies to opening files with Refinery.

![unknown](https://user-images.githubusercontent.com/12814075/72849152-fbb2fc80-3d0a-11ea-9f1b-56c06dbf06b7.png)

**Comment by ShellyHerself** [comment]
That second part looks like a weird edge case with your graphics driver outputting something while kdialog is running. I'll look into it, but this might affect more than just the mek on your system.

**Comment by ShellyHerself** [comment]
The directory not needing to exist is intended behavior. The tools are smart enough to be able to create underlying folders when needed. Including the tags directory.
