### ISSUE TITLE
Clicking "No" when closing a modified tag results in changes being cached

### ISSUE THREAD

**Issue by SnowyMouse** [MosesofEgypt/mozzarilla#24]
After changing tag data, the window will be marked as dirty with an asterisk, indicating that the tag is modified. Attempting to close the window in this state shows a dialog to confirm changes. Clicking "No" to discard the changes closes the tag, but reopening the same tag shows the previous changes still being present rather than completely reopening the tag as expected.

To make matters worse, it isn't marked as dirty with an asterisk anymore, so the user has no idea that they are working with a modified tag (that they just said they didn't want). And even if they did, for some completely insane reason, wanted to save the tag while it's in this state, Mozzarilla won't save it with ctrl-s unless it's modified further to bring back that asterisk.

**Comment by ShellyHerself** [comment]
Tag handler can't find any tags when it is requested to delete from its cache.
(Looking into it)

**Comment by ShellyHerself** [comment]
Should be fixed with https://github.com/MosesofEgypt/binilla/commit/4835dae58b238b1cf28f9790a88eaf4027da1732

I'm going to update the installer to allow to you install the editing kit from the source repos as like a way for beta builds.

Will message you back when that is done.

**Comment by ShellyHerself** [comment]
This bug must have happened with the changes for posix compatibility.

**Comment by ShellyHerself** [comment]
Here is a beta version of the MEK installer. It will allow you to try out the versions on the github master branches.
It's also bigger for 4k viewing pleasure.
[MEK_Installer_beta_2.3.0.pyw.zip](https://github.com/MosesofEgypt/mozzarilla/files/4129351/MEK_Installer_beta_2.3.0.pyw.zip)
